import AppKit

/// The static, monochrome pixel-crab icon shown in the menu bar.
///
/// Loaded as a *template* image so macOS tints it automatically (black on a
/// light menu bar, white on a dark one). Art is generated by
/// `Tools/GenerateMenuBarIcon.swift`.
enum MenuBarIcon {

    /// Display size in points (the 36px @2x art renders crisply at this size).
    private static let pointSize = NSSize(width: 18, height: 18)

    static let image: NSImage = {
        guard let url = Bundle.module.url(forResource: "menubar", withExtension: "png",
                                          subdirectory: "Sprites"),
              let img = NSImage(contentsOf: url) else {
            // Fallback keeps the app usable if the asset is missing.
            return NSImage(systemSymbolName: "ladybug.fill", accessibilityDescription: "KeyboardPet")
                ?? NSImage()
        }
        img.size = pointSize
        img.isTemplate = true
        return img
    }()
}
